get_softwere_net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

urlpatterns = [
    path('almastheadmin/', admin.site.urls),
    path('', include('software.urls')),
    path('email/', include(email_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

software/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from software import views
from .sitemaps import CatagorySitemap, SoftwareSitemap, StaticSitemap

app_name = "software"
handler404 = 'software.views.handler404'

sitemaps = {
    'software': SoftwareSitemap,
    'catagory': CatagorySitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('login', views.loginUser, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('register', views.register, name='register'),
    path('search', views.userSearch, name='search'),
    path('newsletter', views.newsletter, name='newsletter'),
    path('download', views.download, name='download'),
    path('catagory', views.catagory, name='catagory'),
    path('catagory/<str:slug>', views.sub_catagory, name='sub_catagory'),
    path('software', views.all_softwares, name='all_softwares'),
    path('software/<str:slug>', views.softwares, name='softwares'),
    path('profile', views.profile, name='profile'),
    path('like/id=<str:id>/post_id=<str:post_id>', views.like, name='like'),
    path('comment/post_id=<str:post_id>', views.comment, name='comment'),
    path('404', views.handler404, name='handler404'),
    path('auto-suggest', views.auto_suggest, name='auto_suggest'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain')),
]

templates/blog_card.html
{% load static %}

<div class="wrapper row2">
    <section id="latest" class="hoc container clear">
        <div class="sectiontitle">
            <h6 class="heading">All latest blog posts</h6>
            <!-- <p>Et malesuada vitae risus in a enim in metus ultrices tristique</p> -->
        </div>

        <ul class="nospace group">

            <li class="one_third first">
                <article>
                    <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt=""></a>
                        <figcaption>
                            <time datetime="2045-04-06T08:15+00:00"><strong>06</strong> <em>Apr</em></time>
                        </figcaption>
                    </figure>
                    <div class="excerpt">
                        <h6 class="heading">Integer aliquet dignissim tellus</h6>
                        <ul class="nospace meta">
                            <li><i class="fas fa-user"></i> <a href="#">Admin</a></li>
                            <li><i class="fas fa-tags"></i> <a href="#">Tag 1</a>, <a href="#">Tag 2</a></li>
                        </ul>
                        <p>Vestibulum consequat praesent bibendum vehicula mi sed fermentum erat sit amet imperdiet
                            dictum enim lectus [<a href="#">&hellip;</a>]</p>
                        <footer><a class="btn" href="#">Read More</a></footer>
                    </div>
                </article>
            </li>

            <li class="one_third">
                <article>
                    <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt=""></a>
                        <figcaption>
                            <time datetime="2045-04-05T08:15+00:00"><strong>05</strong> <em>Apr</em></time>
                        </figcaption>
                    </figure>
                    <div class="excerpt">
                        <h6 class="heading">Tortor tempus metus neque</h6>
                        <ul class="nospace meta">
                            <li><i class="fas fa-user"></i> <a href="#">Admin</a></li>
                            <li><i class="fas fa-tags"></i> <a href="#">Tag 1</a>, <a href="#">Tag 2</a></li>
                        </ul>
                        <p>Vel elit integer in orci vitae lacus ultricies mattis suspendisse congue sapien vel massa
                            posuere lacinia [<a href="#">&hellip;</a>]</p>
                        <footer><a class="btn" href="#">Read More</a></footer>
                    </div>
                </article>
            </li>

            <li class="one_third">
                <article>
                    <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt=""></a>
                        <figcaption>
                            <time datetime="2045-04-04T08:15+00:00"><strong>04</strong> <em>Apr</em></time>
                        </figcaption>
                    </figure>
                    <div class="excerpt">
                        <h6 class="heading">Phasellus a ipsum eget odio</h6>
                        <ul class="nospace meta">
                            <li><i class="fas fa-user"></i> <a href="#">Admin</a></li>
                            <li><i class="fas fa-tags"></i> <a href="#">Tag 1</a>, <a href="#">Tag 2</a></li>
                        </ul>
                        <p>Fringilla tincidunt proin velit aliquam erat volutpat etiam elementum eros ut ante fusce
                            a lacus ac neque [<a href="#">&hellip;</a>]</p>
                        <footer><a class="btn" href="#">Read More</a></footer>
                    </div>
                </article>
            </li>
        </ul>
        <center>
            <br>
            <a class="btn" href="#">More Blog Posts</a>
        </center>
    </section>
</div>

templates/footer.html
{% load static %}

<div class="wrapper row0">
    <div id="copyright" class="hoc clear">
        <p class="fl_left">{{config.copyright |safe}} - <a href="#">{{config.domain}}</a></p>
    </div>
</div>
<a id="backtotop" href="#top"><i class="fas fa-chevron-up"></i></a>
<script src="{% static 'layout/scripts/jquery.backtotop.js' %}"></script>

templates/footer2.html
<div class="wrapper row2">
    <footer id="footer" class="hoc clear">
        <div class="">
            <h1 class="logoname"><span>{{config.short_name}}</span>{{config.main_domain}}</h1>
            <p class="btmspace-30">{{config.short_description|safe}}</p>
            <ul class="faico clear">
                <li><a class="faicon-dribble" href="{{config.google}}" target="_blank"><i class="fab fa-google"></i></a></li>
                <li><a class="faicon-facebook" href="{{config.facebook}}" target="_blank"><i class="fab fa-facebook"></i></a></li>
                <li><a class="faicon-google-plus" href="{{config.instagram}}" target="_blank"><i class="fab fa-instagram"></i></a></li>
                <li><a class="faicon-linkedin" href="{{config.linkedin}}" target="_blank"><i class="fab fa-linkedin"></i></a></li>
                <li><a class="faicon-twitter" href="{{config.twitter}}" target="_blank"><i class="fab fa-twitter"></i></a></li>
                <li><a class="faicon-vk" href="{{config.github}}" target="_blank"><i class="fab fa-github"></i></a></li>
            </ul>
        </div>
<!-- 
        <div class="one_third">
            <h6 class="heading">Massa hendrerit bibendum</h6>
            <ul class="nospace linklist">
                <li><a href="#">Tincidunt vel vulputate egestas</a></li>
                <li><a href="#">Leo sed porttitor accumsan arcu</a></li>
                <li><a href="#">Aenean ac urna et leo posuere</a></li>
                <li><a href="#">Pretium suspendisse ac elit ut</a></li>
            </ul>
        </div> -->

        <!-- <div class="one_third">
            <h6 class="heading">Subscribe to our newsletter</h6> -->
            <!-- <p class="nospace btmspace-15">Leo integer sem nisl mollis ut ornare eu lobortis eget ante mauris
                tempor.</p> -->
            <!-- <form method="post" action="#">
                <fieldset>
                    <input class="btmspace-15" type="text" value="" placeholder="Name" required>
                    <input class="btmspace-15" type="text" value="" placeholder="Email" required>
                    <button type="submit" value="submit">Submit</button>
                </fieldset>
            </form>
        </div> -->

    </footer>
</div>

templates/headers.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} - {{config.website_name}}</title>
    <link rel="stylesheet" href="{% static 'layout/styles/layout.css' %}">
    <script src="{% static 'layout/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'layout/scripts/jquery.backtotop.js' %}"></script>
    <script src="{% static 'layout/scripts/jquery.mobilemenu.js' %}"></script>
    {% block links %}{% endblock links %} 
</head>

templates/layout.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %} - {{config.website_name}}</title>
  <link rel="stylesheet" href="{% static 'layout/styles/layout.css' %}">

  <link rel="stylesheet" href="{% static 'js/bootstrap/jquery-ui.css' %}">
  <script src="{% static 'js/bootstrap/jquery-1.12.4.js' %}"></script>
  <script src="{% static 'js/bootstrap/jquery-ui.js' %}"></script>

  <script src="{% static 'layout/scripts/jquery.mobilemenu.js' %}"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
  <script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap/popper.min.js' %}"></script>
  <link rel="shortcut icon" href="{{config.website_fabicon}}" type="image/x-icon">
  <link rel="icon" href="{{config.website_fabicon}}" type="image/gif" sizes="16x16">

  <link rel="stylesheet" href="{% static 'css/main_layout.css' %}">
  <script src="{% static 'js/main_layout.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/pre_loader.css' %}">
  <script src="{% static 'js/pre_loader.js' %}"></script>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

  {% block links %}{% endblock links %}

</head>

<!-- {% include 'headers.html' %} -->

<body id="top" class="p-0">

  <div class="pre_loader hidden">
    <img src="{% static 'img/pre_loader.gif' %}" alt="loader" style="pointer-events: none;" title="loader">
  </div>

  {% include 'super_head.html' %}
  {% include 'login_modal.html' %}
  {% include 'register_modal.html' %}
  {% include 'newsletter_modal.html' %}
  {% include 'search_modal.html' %}

  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  {% endif %}

  {% block body %}{% endblock body %}
  {% include 'footer.html' %}

</body>


</html>

templates/login_modal.html
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content card__">
            <div class="modal-header">
                <h4 class="modal-title" id="login">Login</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'software:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password"
                            required>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/navbar.html
<nav id="mainav" class="hoc">
    <ul class="">
        <li class="active"><a href="/index">Home</a></li>
        <li><a class="drop" href="#">Pages</a>
            <ul>
                <li><a href="pages/gallery.html">Gallery</a></li>
                <li><a href="pages/full-width.html">Full Width</a></li>
                <li><a href="pages/sidebar-left.html">Sidebar Left</a></li>
                <li><a href="pages/sidebar-right.html">Sidebar Right</a></li>
                <li><a href="pages/basic-grid.html">Basic Grid</a></li>
                <li><a href="pages/font-icons.html">Font Icons</a></li>
            </ul>
        </li>
        <li><a class="drop" href="#">Dropdown</a>
            <ul>
                <li><a href="#">Level 2</a></li>
                <li><a class="drop" href="#">Level 2 + Drop</a>
                    <ul>
                        <li><a href="#">Level 3</a></li>
                        <li><a href="#">Level 3</a></li>
                        <li><a href="#">Level 3</a></li>
                    </ul>
                </li>
                <li><a href="#">Level 2</a></li>
            </ul>
        </li>
        <li><a href="#">Link Text</a></li>
        <li><a href="#">Link Text</a></li>
        <li><a href="#">Link Text</a></li>
        <li><a href="#">Long Link Text</a></li>
    </ul>
</nav>

templates/newsletter_modal.html
<div class="modal fade" id="newsletter" tabindex="-1" role="dialog" aria-labelledby="modal"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content card__">
            <div class="modal-header">
                <h4 class="modal-title">Subscribe Newsletter</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'software:newsletter' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Your Full Name</label>
                        <input type="name" class="form-control" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" aria-describedby="emailHelp" name="email" required>
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/og-tags.html
<meta property="og:title" content="Open Graph Meta Tags: Everything You Need to Know" />
<meta property="og:url" content="https://ahrefs.com/blog/open-graph-meta-tags/" />
<meta property="og:image" content="https://ahrefs.com/blog/wp-content/uploads/2020/01/fb-open-graph-1.jpg" />
<meta property="og:type" content="article" />
<meta property="og:description" content="Keep it short and sweet. Facebook recommends 2–4 sentences, but that often truncates." />
<meta property="og:locale" content="en_US" />

templates/register_modal.html
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="modal"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content card__">
            <div class="modal-header">
                <h4 class="modal-title">Register</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'software:register' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="fname">First Name</label>
                        <input type="text" name="fname" class="form-control" id="fname" placeholder="First Name" required>
                    </div>
                    <div class="form-group">
                        <label for="lname">Last Name</label>
                        <input type="text" name="lname" class="form-control" id="lname" placeholder="Last Name" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" name="email" class="form-control" id="email"
                            aria-describedby="Enter your valid email address." placeholder="Email Address" required>
                        <small id="email" class="form-text text-muted px-2">We'll never share your email with anyone
                            else.</small>
                    </div>
                    <div class="form-group mt-2">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label for="repassword">Re-Password</label>
                        <input type="password" name="repassword" class="form-control" id="repassword" placeholder="Re-Password"
                            required>
                    </div>
                    <div class="row px-2">
                        <button type="submit" class="btn btn-primary w-50">Submit</button>
                        <button type="reset" class="btn btn-danger w-50">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/search_modal.html
<!-- {% load static %} -->
<!-- {% block links %}
<script src="{% static 'jquery-ui.js' %}"></script>
{% endblock links %} -->

<div class="modal fade" id="search" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog ui-front" role="document">
        <div class="modal-content card__">
            <div class="modal-header">
                <h4 class="modal-title">Search</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'software:search' %}" method="GET">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="search">Search Your Interest</label>
                        <input type="search" class="form-control" name="query" id="query" placeholder="Search" required>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    $(function () {
        $("#query").autocomplete({
            source: "{% url 'software:auto_suggest' %}",
        });
    });
</script>

templates/software_card.html
{% load static %}
<div class="wrapper row3">
    <main class="hoc container clear">
        <div class="sectiontitle">
            <h6 class="heading">All latest softwares</h6>
        </div>

        <ul class="nospace group overview">

            <li class="one_third">
                <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt="image" title="Image"
                            style="pointer-events: none;"></a>
                    <figcaption>
                        <h6 class="heading">Dapibus pede tristique</h6>
                        <p>Congue quam erat et dui morbi at sapien non enim blandit.</p>
                    </figcaption>
                </figure>
            </li>

            <li class="one_third">
                <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt="image" title="Image"
                            style="pointer-events: none;"></a>
                    <figcaption>
                        <h6 class="heading">Interdum morbi posuere</h6>
                        <p>Etiam consequat arcu accumsan commodo luctus nibh fringilla.</p>
                    </figcaption>
                </figure>
            </li>

            <li class="one_third">
                <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt="image" title="Image"
                            style="pointer-events: none;"></a>
                    <figcaption>
                        <h6 class="heading">Augue non vehicula</h6>
                        <p>Erat neque et tortor ut molestie ultricies quam aliquam.</p>
                    </figcaption>
                </figure>
            </li>

            <li class="one_third">
                <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt="image" title="Image"
                            style="pointer-events: none;"></a>
                    <figcaption>
                        <h6 class="heading">Erat volutpat integer</h6>
                        <p>Posuere vulputate leo nullam eu tellus phasellus aliquam.</p>
                    </figcaption>
                </figure>
            </li>

            <li class="one_third">
                <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt="image" title="Image"
                            style="pointer-events: none;"></a>
                    <figcaption>
                        <h6 class="heading">Tellus ut libero etiam</h6>
                        <p>Ut metus quisque pretium nunc fermentum volutpat velit sed.</p>
                    </figcaption>
                </figure>
            </li>

            <li class="one_third">
                <figure><a href="#"><img src="{% static 'img/theme_bg.jpg' %}" alt="image" title="Image"
                            style="pointer-events: none;"></a>
                    <figcaption>
                        <h6 class="heading">Dictum bibendum velit</h6>
                        <p>Nulla iaculis pellentesque nunc felis tristique vel ultrices.</p>
                    </figcaption>
                </figure>
            </li>

        </ul>
        <div class="clear"></div>
    </main>
</div>

templates/super_head.html
<noscript>Your browser don't support javascript.</noscript>
<div class="wrapper row0">
    <div id="topbar" class="hoc clear">
        <div class="fl_left">
            <ul class="nospace">
                <li><a href="{% url 'software:index' %}"><i class="fas fa-home fa-lg"></i></a></li>
                <li><a href="{% url 'software:about' %}">About</a></li>
                <li><a href="{% url 'software:contact' %}">Contact</a></li>
                <li><a href="#" data-toggle="modal" data-target="#search">Search</a></li>
                <li><a href="{% url 'software:catagory' %}">Catagory</a></li>
                {% if request.user.is_anonymous %}
                <li><a href="#" data-toggle="modal" data-target="#login">Login</a></li>
                <li><a href="#" data-toggle="modal" data-target="#register">Register</a></li>
                {% else %}
                <li><a href="/profile">Profile</a></li>
                <li><a href="/logout">Logout</a></li>
                {% endif %}
                
            </ul>
        </div>
        <div class="fl_right">
            <ul class="nospace">
                <li><i class="fas fa-phone rgtspace-5"></i><a href="callto:{{config.number}}">{{config.number}}</a></li>
                <li><i class="fas fa-envelope rgtspace-5"></i><a href="mailto:{{config.email}}">{{config.email}}</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- <div class="wrapper row1">
    <header id="header" class="hoc clear">
        <div id="logo" class="one_half first">
            <h1 class="logoname"><a
                    href="{% url 'software:index' %}"><span>{{config.website_name}}</span>{{config.top_domain}}</a></h1>
        </div>
    </header>
</div> -->